### PR TITLE
Clan Sync Fixes

### LINKED ISSUE #681: Sync Clan Automated Events
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

During the course of the game, the clan is automatically updated by tick events or other kinds of events.

Create sync messages and handlers on the following:
- Server
- Client
- GameInterface

for every automatic clan event that requires syncing.

Create `Coop.Core` integration tests for all new command messages that are sent to the GameInterface

## Intended Design

N/A

## Location

Create a new branch based from development

## Related Issues

N/A

## Requirements

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### PR DESCRIPTION
**Pull request by garrettluskey**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

Clan sync was crashing the client

## What is the new behaviour?

Client is now able to join, currently too many influence change messages are being sent from the client

## Other information

### CODE REVIEW

File: source/GameInterface/Services/Clans/Patches/ClanChangeInfluencePatch.cs [hunk 1]
```diff
@@ -16,6 +17,8 @@ public class ClanChangeInfluencePatch
 
         static bool Prefix(Clan clan, float amount)
         {
+            if (PolicyProvider.AllowOriginalCalls) return true;
+
             CallStackValidator.Validate(clan, AllowedInstance);
 
             if (AllowedInstance.IsAllowed(clan)) return true;
```
Comment (EgardA) [inline source/GameInterface/Services/Clans/Patches/ClanChangeInfluencePatch.cs:28]:
```suggestion
            if (AllowedInstance.IsAllowed(clan)) return true;
            if (ModInformation.IsClient && clan != Clan.PlayerClan) return false;
```

Comment (EgardA) [reply source/GameInterface/Services/Clans/Patches/ClanChangeInfluencePatch.cs:28]: This should work well imo, maybe there's a variable in clan that can be used instead of Clan.PlayerClan

**Review by EgardA — APPROVED** [review]
If it works, it works. 

Just the one comment
