### PR TITLE
Tranpiler for town daily tick

### LINKED ISSUE #757: [Report] Fief does not sync correctly
## Severity of issue/bug

- [ ] High
- [x] Average
- [ ] Low

## Describe the issue/bug that appears (Image and/or text should work)

``` [HarmonyPatch(typeof(Fief),"FoodStocks",MethodType.Setter)]``` are not called by the game when a food stock change
## Steps to reproduce

Let the game run for some seconds, when a fief food change should change (it change every seconds on the map). The prefix patch is not trigger

### PR DESCRIPTION
**Pull request by thomas-soutif**
handle the case of the foodStock of a fief
I should modify it because the food stack value is not exactly the one we want, but Im' in good progress

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the new behaviour?

Resolves #757 

## Other information

### CODE REVIEW

**Comment by thomas-soutif** [comment]
still investigating

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        int setterLastIdx = instructions.FindLastIndex(i => i.opcode == Call.opcode && i.operand as MethodInfo == foodStocksSetter);
+        if (setterLastIdx == -1) return instrs;
+
+        instructions.InsertRange(setterLastIdx, new CodeInstruction[]
+        {
+            new CodeInstruction(OpCodes.Ldarg_0),
+            new CodeInstruction(OpCodes.Call, AccessTools.Method(typeof(TownDailyTickPatch), "LogFoodStock"))
+        });
+        
+        return instructions;
```
Comment (garrettluskey) [inline source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: Currently this will only patch the last FoodStocks set

This also does not block setting on the client

Below will replace the call with your method

The stack will also contain the new food stocks value so you will have to set it yourself for more control

```suggestion
        foreach (var instriction in instrs)
{
    if (i.opcode == Call.opcode && i.operand as MethodInfo == foodStocksSetter)
    {
        yield return new CodeInstruction(OpCodes.Ldarg_0);
        yield return new CodeInstruction(OpCodes.Call, AccessTools.Method(typeof(TownDailyTickPatch), "LogFoodStock"));
        continue;
    }

    yield return instriction
}
```

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        
+    }
+
+    public static void LogFoodStock(Fief fief)
```
Comment (garrettluskey) [inline source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: Update to match new patch

```suggestion
    public static void LogFoodStock(float newValue, Fief fief)
```

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    {
+        // If it's the client, return
+        if (!ModInformation.IsServer) return;
```
Comment (garrettluskey) [inline source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: No '!' is less confusing at a glance

```suggestion
        if (ModInformation.IsClient) return;
```

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+        
+        var message = new FiefFoodStockChanged(fief.StringId, fief.FoodStocks);
```
Comment (garrettluskey) [inline source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]:
```suggestion
        fief.FoodStocks = newValue;
        var message = new FiefFoodStockChanged(fief.StringId, fief.FoodStocks);
```

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs (hunk 1 above)
Comment (thomas-soutif) [reply source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: When I remplace with this code, I have this crash :

image

Comment (thomas-soutif) [reply source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: The crash seem to come from the yield return

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs (hunk 2 above)
Comment (thomas-soutif) [reply source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: Because we get from the stack the Ldarg_0, that represent the "fief" instance , putting a float newValue make the program crash
we should found the value return by the previous stack (get_foodStack) in the dailyTick() method
image

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs (hunk 1 above)
Comment (thomas-soutif) [reply source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: So I was able to make it work without crash by removing the new code insruction(OpCodes.Ldarg0)
the crash occurs because we add two new code instruction for one instruction replace
but now I have this as a result : 
image
the fief instance return here for exemple is a list of "village", maybe because 3 villages have the same food stock in same time ?

Comment (thomas-soutif) [reply source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: Finally make it works !
```
    foreach (var instruction in instrs)
    {
        if (instruction.opcode == Call.opcode && instruction.operand as MethodInfo == foodStocksSetter)
        {
	    yield return new CodeInstruction(OpCodes.Call, AccessTools.Method(typeof(TownDailyTickPatch), "LogFoodStock"));
            //yield return new CodeInstruction(OpCodes.Ldarg_0);
            continue;
        }
        yield return instruction;
    }
    
}

public static void LogFoodStock(Fief fief, float value)
```
so I remove the Ldarg_0 and change the order of the parameter that take LogFoodStock, the problem was there

**Comment by thomas-soutif** [comment]
Bug fixed, ready for review

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+    // Get the setter method for the FoodStocks property
+    private static MethodInfo foodStocksSetter = foodStocksProperty.GetSetMethod(true);
+
+    [HarmonyTranspiler]
+    private static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instrs)
+    {
+        
+        foreach (var instruction in instrs)
+        {
+            if (instruction.opcode == Call.opcode && instruction.operand as MethodInfo == foodStocksSetter)
```
Comment (garrettluskey) [inline source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]:
```suggestion
            if (instruction.opcode == Call.opcode && instruction.operand as MethodInfo == AccessTools.PropertySetter(typeof(Fief), "FoodStocks"))
```

File: source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+using GameInterface.Services.Fiefs.Patches;
+
+[HarmonyPatch(typeof(Town), "DailyTick")]
+public static class TownDailyTickPatch
+{
+    // Get the PropertyInfo for the FoodStocks property
+    private static PropertyInfo foodStocksProperty = typeof(Fief).GetProperty("FoodStocks");
+
+    // Get the setter method for the FoodStocks property
+    private static MethodInfo foodStocksSetter = foodStocksProperty.GetSetMethod(true);
```
Comment (garrettluskey) [inline source/GameInterface/Services/Towns/Patches/DailyTickTownPatch.cs]: This data is stored the entire lifetime of the program, if they are not used outside the transpiler use the "=>" operator or move it into the transpiler like suggested
```suggestion
```

**Review by garrettluskey — CHANGES_REQUESTED** [review]

**Review by garrettluskey — APPROVED** [review]
