### PR TITLE
Missile crash fix (perhaps)

### LINKED ISSUE #559: Missiles Crash
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Missiles crash the game due `NetworkMissileRegistry` recieving `PeerMissileAdded` from the sending peer before `PeerConnected` is processed.

Find a solution for this problem.

## Intended Design

N/A

## Location

Create a new branch from `arena-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### PR DESCRIPTION
**Pull request by EgardA**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the new behaviour?

Resolves #559 maybe?

## Other information

### CODE REVIEW

File: source/Missions/Services/Missiles/NetworkMissileRegistry.cs [hunk 1]
```diff
@@ -63,6 +65,12 @@ private void Handle_PeerConnected(MessagePayload<PeerConnected> obj)
             var peer = obj.What.Peer;
 
             peerMissileRegistries.TryAdd(peer.Id, new PeerMissileIndexMap(peer.Id));
+
+            foreach(MessagePayload<PeerMissileAdded> payload in queuedMissiles)
+            {
+                if (payload.Who != peer) continue;
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/NetworkMissileRegistry.cs]: This will always be true no?

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/NetworkMissileRegistry.cs (hunk 1 above)
Comment (EgardA) [reply source/Missions/Services/Missiles/NetworkMissileRegistry.cs]: I guess because payload.Who is a an object and not a NetPeer, updated this to instead use the NetPeer ID. The ID's are most of the time the same but there will be missiles in case of two joining at the same time where they might differ.

**Review by garrettluskey — APPROVED** [review]
