### PR TITLE
Settlement menu open twice fix

### LINKED ISSUE #134: Menu on settlement opens twice
Steps to reproduce
  - Get into a settlement
  - When menu pops up press "Leave"

What should happen
  Menu would open again

Expected behaviour
  Menu gets closed

Possible Problem/Solution
  Unknown yet

### PR DESCRIPTION
**Pull request by DiMiGi**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?
When leaving a settlement the menu opens again, after pressing a second time the "Leave" button the party would leave the settlement

## What is the new behaviour?
Resolves #134 

When leaving a settlement the menu opens once

## Other information

### CODE REVIEW

File: source/Coop/Mod/Persistence/Party/MovementData.cs [hunk 1]
```diff
@@ -93,6 +93,20 @@ public bool NearlyEquals(MovementData other)
...
+        public override bool Equals(Object obj)
+        {
+            if (!(obj is MovementData))
+            {
+                return false;
+            }
+
+            MovementData other = (MovementData)obj;
+            return DefaultBehaviour.Equals(other.DefaultBehaviour) &&
+                   TargetPosition.Equals(other.TargetPosition) &&
```
Comment (araex) [inline source/Coop/Mod/Persistence/Party/MovementData.cs]: Do you really want to exactly compare the float coordinates? I think the position should be compared using `Compare.CoordinatesEqual(Vec2 a, Vec2 b)`. As map coordinates are compressed for synchronization (`Compression.Coordinate2d`), floating point errors are to be expected. I realize you're using the new Equals method to compare local values only, but for the sake of usability i think it would be best to implement it using the coordinate compare anyways. This might prevent comparision errors in the future. Or what do you think?

Looking at the class, there's already a `MovementData.NearlyEquals(MovementData other)` which should use `Compare.CoordinatesEqual(Vec2 a, Vec2 b)` as well. I think it would be good if you combined `Equals` and `NearlyEquals` into a single method, probably just `Equals`.

**Review by araex — COMMENTED** [review]
Looks good, but i'd like to discuss the implementation of `MovementData.Equals`. I think it should compensate for the floating point errors expected due to the synchronization compression. Even if it currently is only used to compare non-synchronized values. But i'm not sure what the best practices are in C# regarding `Equals`. 

Does anyone else have an opinion on this? Otherwise i'll leave it up to @DiMiGi to decide.

File: source/Coop/Mod/Persistence/Party/MovementData.cs (hunk 1 above)
Comment (DiMiGi) [reply source/Coop/Mod/Persistence/Party/MovementData.cs]: You're right, I've changed the implementation but instead of using CoordinatesEqual I've used the NearlyEquals implemented by TaleWorlds in the Vec2 Class, using the precision in the Compare Class.

image

**Comment by DiMiGi** [comment]
As far as I know `Equals` is used to compare objects and not to know if these objects are the same instance, that means `Equals` should be used in this case. Also, it brings abstraction when using `System.Object` instances, because casting won't be needed, as you could see in source/Sync/FieldChangeBuffer.cs file, where `Equals` is being used in a `Object` type instance, but instead of using the `Object` type implementation it's actually using the `Equals` of the `MovementData` type.

**Review by araex — APPROVED** [review]
