### PR TITLE
Add fixes to support game version 1.5.9

### LINKED ISSUE #180: Update Mod for 1.5.9 Compatability

### PR DESCRIPTION
**Pull request by MaxBosse**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?
Currently you are unable to build the project with the game version 1.5.9

## What is the new behaviour?
This PR fixes all errors during the build of the project and allows you to start the game with the mod and host a coop campaign.

## Other information
The OnLordPartySpawned event was removed in the last update. To compensate I wrote a patch that executes a custom event after a call to InitializeLordPartyProperties.
In 1.5.8 the event was called at the end of InitializeLordPartyProperties, which is why I decided to use a suffix instead of the usualy prefix.

### CODE REVIEW

File: source/Coop/Mod/Persistence/MobilePartyEntityManager.cs [hunk 1]
```diff
@@ -116,7 +116,7 @@ private void InitRoom(RailServerRoom room)
             CampaignEvents.OnPartyRemovedEvent.AddNonSerializedListener(this, OnPartyRemoved);
             
             CampaignEvents.MobilePartyCreated.AddNonSerializedListener(this, OnPartyAdded);
-            CampaignEvents.OnLordPartySpawnedEvent.AddNonSerializedListener(this, OnPartyAdded);
+            LordPartyComponentPatch.OnLordPartySpawned += (sender, e) => OnPartyAdded(e);
```
Comment (p-JordanStiebritz) [inline source/Coop/Mod/Persistence/MobilePartyEntityManager.cs]: Might be able to just get away with removing this line wholly rather than adding `LordPartyComponentPatch`. Since 1.5.9 changed it so that lord parties are just mobile parties, we would probably be handling the party being added twice for players. (Might be a reason why the main party spawned and AI took control of it?)

Comment (MaxBosse) [reply source/Coop/Mod/Persistence/MobilePartyEntityManager.cs]: Removing the patch indeed fixed the duplicate party. Thanks!

**Comment by p-JordanStiebritz** [comment]
This PR looks fine to me. I think there is a previous existing issue where when you exit, it doesn't actually despawn you from the game. This could be fine, but requires us to not register the client's party a second time or to correctly unregister it when player exits or the game crashes. Any opinions on the persistent client party @garrettluskey ?

**Review by garrettluskey — APPROVED** [review]
