### PR TITLE
Settlement Enter Spam & Leave Crash fix

### LINKED ISSUE #686: Town Enter/Town Leave Crash
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Leaving or entering castles/settlements crashes the client.

Find why this is and resolve the issue

## Intended Design

N/A

## Location

Create a new branch from development

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #688: Enter Settlement Message Spam
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

When a settlement is attempted to be entered, the client spams the server with requests if there is some latency between the client and server.

Ensure that the request message is sent once when trying to enter any settlement

## Intended Design

N/A

## Location

Create a new branch based from development

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### PR DESCRIPTION
**Pull request by EgardA**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

bug and crash

## What is the new behaviour?

Resolves #688 #686

bug and crash no more

## Other information

### CODE REVIEW

File: source/GameInterface/Services/Settlements/Patches/DisablePlayerTownVisitCampaignBehavior.cs [hunk 1]
```diff
@@ -63,7 +63,7 @@ static bool DisableTownMarket()
     [HarmonyPatch("game_menu_town_town_streets_on_consequence")]
     static bool DisableTownCenter()
     {
-        return false;
+        return true;
```
Comment (garrettluskey) [inline source/GameInterface/Services/Settlements/Patches/DisablePlayerTownVisitCampaignBehavior.cs]: keep this false until the functionality is added

File: source/GameInterface/Services/Settlements/Patches/DisablePlayerTownVisitCampaignBehavior.cs [hunk 2]
```diff
@@ -93,7 +93,7 @@ static bool DisableTownKeep()
     [HarmonyPatch("game_menu_village_village_center_on_consequence")]
     static bool DisableVillageCenter()
     {
-        return false;
+        return true;
```
Comment (garrettluskey) [inline source/GameInterface/Services/Settlements/Patches/DisablePlayerTownVisitCampaignBehavior.cs]: keep this false until the functionality is added

File: source/GameInterface/Services/MobileParties/Patches/PlayerLeaveSettlementPatch.cs [hunk 3]
```diff
@@ -34,6 +34,8 @@ public static void OverrideLeaveConsequence()
             LeaveSettlementActionPatches.AllowedInstance.Instance = MobileParty.MainParty;
             PlayerEncounter.Finish(true);
             Campaign.Current.SaveHandler.SignalAutoSave();
+
+            EncounterManagerPatches.inSettlement = false;
```
Comment (garrettluskey) [inline source/GameInterface/Services/MobileParties/Patches/PlayerLeaveSettlementPatch.cs]: Move this into a patch for the PlayerEncounter.Finish method in the PlayerEncounterPatches.cs file

File: source/GameInterface/Services/MobileParties/Patches/PlayerEncounterPatches.cs [hunk 4]
```diff
@@ -19,6 +19,7 @@ namespace GameInterface.Services.MobileParties.Patches;
 [HarmonyPatch(typeof(EncounterManager))]
 internal class EncounterManagerPatches
 {
+    public static bool inSettlement = false;
```
Comment (garrettluskey) [inline source/GameInterface/Services/MobileParties/Patches/PlayerEncounterPatches.cs]: Make this private

**Review by garrettluskey — CHANGES_REQUESTED** [review]

**Review by garrettluskey — APPROVED** [review]
