### PR TITLE
"Drops" & Pickups

### LINKED ISSUE #514: Create Weapon Pickup Handler
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create a new Handler class under `Services/Agents/Handlers` for sending and receiving weapon pickup events.

Create a weapon pickup harmony patch that detects when a weapon is picked up.
Create an internal event that the harmony patch publishes.

In the Handler class handle the internal event and send a new event over the network.
In the Handler class handle the respective incoming network event.

## Intended Design

N/A

## Location

Create a new branch from `arena-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #515: Create Weapon Drop Handler
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create a new Handler class under `Services/Agents/Handlers` for sending and receiving weapon drop events.

Create a weapon drop harmony patch that detects when a weapon is dropped up.
Create an internal event that the harmony patch publishes.

In the Handler class handle the internal event and send a new event over the network.
In the Handler class handle the respective incoming network event.

## Intended Design

N/A

## Location

Create a new branch from `arena-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #527: Create BowMissile Handler
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create a post-fix event message for `AddMissileSingleUsageAux` method in the `Mission` taleworlds class. For reference see `AgentKilledPatch.cs` and `AgentDied.cs`

Put all new classes in their respective folders under Services/Projectiles

Create a new handler class that handles this new message.
In this handler, if the agent is controlled, send a network message.

On receive from the network, call `AddMissileSingleUsageAux` with the parameters from the message.
On receive from the network, add the new entity and index that was in the message to `_missiles`.
NOTE: `_missiles` is a field in the `Mission` class. We must have the same functionality in the `if (!flag)` block in `OnAgentShootMissile` in the `Mission` class.

All new classes should have xml summary comments for public methods and the class itself.
Each handler method should have an associated unit test.

## Intended Design

N/A

## Location

Respective folders under Services/Projectiles
Create a new branch based from `arena-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #528: Create ThrownMissile Handler
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create a post-fix event message for `AddMissileAux` method in the `Mission` taleworlds class. For reference see `AgentKilledPatch.cs` and `AgentDied.cs`

Put all new classes in their respective folders under Services/Projectiles

Create a new handler class that handles this new message.
In this handler, if the agent is controlled, send a network message.

On receive from the network, call `AddMissileAux` with the parameters from the message.
On receive from the network, add the new entity and index that was in the message to `_missiles`.
NOTE: `_missiles` is a field in the `Mission` class. We must have the same functionality in the `if (!flag)` block in `OnAgentShootMissile` in the `Mission` class.

All new classes should have xml summary comments for public methods and the class itself.
Each handler method should have an associated unit test.

## Intended Design

N/A

## Location

Respective folders under Services/Projectiles
Create a new branch based from `arena-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #536: OnFocus Crash
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

When a highlight on a picked up item happens, the game can crash.

## Intended Design

N/A

## Location

N/A

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #537: Transfer Agent MissionEquipment
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

When a new item is picked up, the Hero Equipment becomes stale. Instead of sending the hero's equipment, transfer the agents MissionEquipment.

## Intended Design

N/A

## Location

Create a new branch from `arena-vertical-slice`
Replace `Equipment` in `NetworkMissionJoinInfo` with `MissionEquipment`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### LINKED ISSUE #540: Sync health on join in battles
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Health on join is not synced, joining when a player is damage will result in desynced deaths.

## Intended Design

Synced deaths and health.

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

### PR DESCRIPTION
**Pull request by EgardA**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

Pickups and Drops not synced

## What is the new behaviour?

Resolves 
- #515 
- #514 
- #527 
- #528
- #516

Weapon Pickup (Picks up and adds the weapon to inventory, does not remotely destroy the entity)
Weapon Drops (Removes the weapon on drop from remote, does not remotely spawn entity until missiles are synced)

## Other information

### CODE REVIEW

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+        public static void WeaponDropRecieve(MessagePayload<WeaponDropExternal> obj)
+        { 
+            NetworkAgentRegistry.Instance.TryGetAgent(obj.What.AgentGuid, out Agent agent);
+
+            agent.RemoveEquippedWeapon(obj.What.EquipmentIndex);
+        }
+    }
+
+    [HarmonyPatch(typeof(Agent), "DropItem")]
+    public class WeaponDropHandlerPatch
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Move this into the patches folder

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using TaleWorlds.Core;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    public class WeaponDropHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: make everything in this class non-static. Also instantiate these handlers in AutoFac using AutoActivate()

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+                missionWeapon.GetAmmoWeaponStatsData(),
+                null,
+                false,
+                false
+                });
+        }
+    }
+
+    [HarmonyPatch(typeof(Agent), "EquipWeaponFromSpawnedItemEntity")]
+    public class WeaponPickupHandlerPatch
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Move this to the patches folder in a new class

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 4]
```diff
@@ -55,6 +56,10 @@ public class CoopArenaController : MissionBehavior, IDisposable
             _networkMessageBroker.Subscribe<AgentDamageData>(Handle_AgentDamage);
             _networkMessageBroker.Subscribe<AgentShoot>(Handle_AgentShoot);
             _networkMessageBroker.Subscribe<AgentDied>(Handler_AgentDeath);
+            _networkMessageBroker.Subscribe<WeaponDropInternal>(WeaponDropHandler.WeaponDropSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]: move all events to their respective classes. i.e. weapondrop to the weapon drop handler

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+using System.Linq;
+using System.Reflection;
+using System.Text;
+using System.Threading.Tasks;
+using TaleWorlds.Core;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    public class WeaponPickupHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: make everything in this class non-static. Also instantiate these handlers in AutoFac using AutoActivate()

File: source/Missions/Services/Agents/Messages/WeaponPickupInternal.cs [hunk 6]
```diff
@@ -0,0 +1,28 @@
+﻿using Common.Messaging;
+using System;
+using TaleWorlds.Core;
+using TaleWorlds.Engine;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Messages
+{
+    public readonly struct WeaponPickupInternal : IEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/WeaponPickupInternal.cs]: Rename this to `WeaponPickedup` for consistency

File: source/Missions/Services/Agents/Messages/WeaponPickupExternal.cs [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+using ProtoBuf;
+using Serilog.Core;
+using System;
+using System.Diagnostics;
+using TaleWorlds.Core;
+
+namespace Missions.Services.Agents.Messages
+{
+    [ProtoContract(SkipConstructor = true)]
+    public class WeaponPickupExternal : INetworkEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/WeaponPickupExternal.cs]: Rename this to `NetworkWeaponPickedup` for consistency

File: source/Missions/Services/Agents/Messages/WeaponDropExternal.cs [hunk 8]
```diff
@@ -0,0 +1,24 @@
+﻿using Common.Messaging;
+using ProtoBuf;
+using System;
+using TaleWorlds.Core;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Messages
+{
+    [ProtoContract(SkipConstructor = true)]
+    public readonly struct WeaponDropExternal : INetworkEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/WeaponDropExternal.cs]: Rename this to `NetworkWeaponDropped` for consistency

File: source/Missions/Services/Agents/Messages/WeaponDropInternal.cs [hunk 9]
```diff
@@ -0,0 +1,19 @@
...
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Messages
+{
+    public readonly struct WeaponDropInternal : IEvent
+    {
+        public Agent Agent { get; }
+        public EquipmentIndex EquipmentIndex { get; }
+
+        public WeaponDropInternal(Agent agent, EquipmentIndex equipmentIndex)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/WeaponDropInternal.cs]: Rename this to `WeaponDropped` for consistency

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/MissionModule.cs [hunk 10]
```diff
@@ -24,6 +25,12 @@ protected override void Load(ContainerBuilder builder)
             }
 
             // Non interface classes
+            builder.RegisterType<CoopMissionNetworkBehavior>().AsSelf();
+            builder.RegisterType<CoopArenaController>().AsSelf();
+            builder.RegisterType<NetworkConfiguration>().AsSelf();
```
Comment (garrettluskey) [inline source/Missions/MissionModule.cs:30]: This is already registered

File: source/Missions/MissionModule.cs [hunk 11]
```diff
@@ -24,6 +25,12 @@ protected override void Load(ContainerBuilder builder)
             }
 
             // Non interface classes
+            builder.RegisterType<CoopMissionNetworkBehavior>().AsSelf();
+            builder.RegisterType<CoopArenaController>().AsSelf();
```
Comment (garrettluskey) [inline source/Missions/MissionModule.cs:29]: This is already registered

File: source/Missions/MissionModule.cs [hunk 12]
```diff
@@ -24,6 +25,12 @@ protected override void Load(ContainerBuilder builder)
...
+            builder.RegisterType<NetworkConfiguration>().AsSelf();
+            builder.RegisterType<MovementHandler>().AsSelf();
```
Comment (garrettluskey) [inline source/Missions/MissionModule.cs]: These are already registered

File: source/Missions/MissionModule.cs [hunk 13]
```diff
@@ -24,6 +25,12 @@ protected override void Load(ContainerBuilder builder)
...
+            builder.RegisterType<WeaponDropHandler>().AsSelf().AutoActivate();
+            builder.RegisterType<WeaponPickupHandler>().AsSelf().AutoActivate();
```
Comment (garrettluskey) [inline source/Missions/MissionModule.cs]: Make these `InstancePerLifetimeScope`

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 14]
```diff
@@ -125,7 +121,7 @@ private void Handle_AgentDamage(MessagePayload<AgentDamageData> payload)
                 _agentRegistry.ControlledAgents.TryGetValue(agentDamaData.AttackerAgentId, out effectorAgent);
             }
 
-            if (effectedAgent == null) return;
+            if (effectorAgent == null) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]: this was changed in `arena-vertical-slice`. Revert this change

File: source/Missions/Services/Agents/Messages/NetworkWeaponPickedup.cs [hunk 15]
```diff
@@ -0,0 +1,123 @@
...
+        public NetworkWeaponPickedup(Guid agentId, EquipmentIndex equipmentIndex, ItemObject weaponObject, ItemModifier itemModifier, Banner banner)
+        {
+            AgentId = agentId;
+            EquipmentIndex = equipmentIndex;
+            ItemObject = weaponObject;
+            ItemModifier = itemModifier;
+            Banner = banner;
+        }
+
+        public NetworkWeaponPickedup() { }
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/NetworkWeaponPickedup.cs]: Remove this, it's not used

File: source/MissionTests/NetworkAgentRegistryTests.cs [hunk 16]
```diff
@@ -35,5 +36,26 @@ public void FullTestLocal()
...
+            Guid localGuid = Guid.NewGuid();
+            networkAgentRegistry.RegisterControlledAgent(localGuid, localAgent);
+
+            Agent remoteAgent = (Agent)FormatterServices.GetUninitializedObject(typeof(Agent));
+            remoteAgent.Age = 10;
+            Guid remoteGuid = Guid.NewGuid();
+            NetPeer netPeer = (NetPeer)FormatterServices.GetUninitializedObject(typeof(NetPeer));
+            networkAgentRegistry.RegisterNetworkControlledAgent(netPeer, remoteGuid, remoteAgent);
+
+            networkAgentRegistry.TryGetAgent(remoteGuid, out Agent remoteTestAgent);
```
Comment (garrettluskey) [inline source/MissionTests/NetworkAgentRegistryTests.cs]: Rename `remoteTestAgent` to something like `resolvedAgent` for clarity

File: source/MissionTests/NetworkAgentRegistryTests.cs [hunk 17]
```diff
@@ -35,5 +36,26 @@ public void FullTestLocal()
...
+            networkAgentRegistry.TryGetAgentId(remoteTestAgent, out Guid remoteTestId);
```
Comment (garrettluskey) [inline source/MissionTests/NetworkAgentRegistryTests.cs]: `remoteTestId` isn't used, recommend removing line

File: source/Missions/Services/Agents/Patches/AgentKilledPatch.cs [hunk 18]
```diff
@@ -1,4 +1,4 @@
-﻿using Common.Messaging;
+﻿    using Common.Messaging;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Patches/AgentKilledPatch.cs]: Please revert this

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 19]
```diff
@@ -190,58 +187,170 @@ private void Handle_JoinInfo(MessagePayload<NetworkMissionJoinInfo> payload)
...
             for (int i = 0; i < joinInfo.UnitIdString?.Length; i++)
             {
                 Agent tempAi = SpawnAgent(joinInfo.UnitStartingPosition[i], CharacterObject.Find(joinInfo.UnitIdString[i]), true);
-                
+
                 _agentRegistry.RegisterNetworkControlledAgent(netPeer, joinInfo.UnitId[i], tempAi);
             }
         }
 
         public override void OnAgentShootMissile(Agent shooterAgent, EquipmentIndex weaponIndex, Vec3 position, Vec3 velocity, Mat3 orientation, bool hasRigidBody, int forcedMissileIndex)
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]: Instead of this, create postfix events for `AddMissileSingleUsageAux` and `AddMissileAux`.
Create handlers for the respective messages created by those.
Send network events if the agent is controlled. Call the same methods on the client and add that missile to the `_missiles` list similar to `OnAgentShootMissile`.

I will also update the issue with these needed updates.

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 20]
```diff
@@ -190,58 +187,170 @@ private void Handle_JoinInfo(MessagePayload<NetworkMissionJoinInfo> payload)
...
+            {
+                num3 = __result;
             }
         }
 
-        private static MethodInfo OnAgentShootMissileMethod = typeof(Mission).GetMethod("OnAgentShootMissile", BindingFlags.NonPublic | BindingFlags.Instance);
-        private static FieldInfo Mission_missiles = typeof(Mission).GetField("_missiles", BindingFlags.NonPublic | BindingFlags.Instance);
+        private static int num3;
+
         private void Handle_AgentShoot(MessagePayload<AgentShoot> payload)
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]: This should be in it's own handler

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 21]
```diff
@@ -311,21 +420,24 @@ private Agent SpawnPlayerAgent(CharacterObject character, MatrixFrame frame)
             {
                 agent = Mission.Current.SpawnAgent(agentBuildData);
                 agent.FadeIn();
+
+
+
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]:
```suggestion
```

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 22]
```diff
@@ -0,0 +1,47 @@
...
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: This requires commenting also create a test case for each function. Create a new test file for this class in a similar directory structure

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 23]
```diff
@@ -0,0 +1,64 @@
...
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: This requires commenting also create a test case for each function. Create a new test file for this class in a similar directory structure

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 24]
```diff
@@ -55,6 +57,7 @@ public class CoopArenaController : MissionBehavior, IDisposable
             _networkMessageBroker.Subscribe<AgentDamageData>(Handle_AgentDamage);
             _networkMessageBroker.Subscribe<AgentShoot>(Handle_AgentShoot);
             _networkMessageBroker.Subscribe<AgentDied>(Handler_AgentDeath);
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]: Rename method to `Handle_AgentDeath`

File: source/Missions/Services/Arena/CoopArenaController.cs [hunk 25]
```diff
@@ -190,58 +187,170 @@ private void Handle_JoinInfo(MessagePayload<NetworkMissionJoinInfo> payload)
...
-                shot.WeaponIndex, 
-                shot.Position,
-                shot.Velocity, 
-                shot.Orientation, 
-                shot.HasRigidBody, 
-                true, 
-                shot.ForcedMissileIndex });
         }
 
         private void Handler_AgentDeath(MessagePayload<AgentDied> obj)
```
Comment (garrettluskey) [inline source/Missions/Services/Arena/CoopArenaController.cs]: Could you move this to it's own class, comment, and create a test for this method? It will also need to be autoactivated.

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 26]
```diff
@@ -0,0 +1,179 @@
...
+        private byte[] _packedItemModifier;
+
+        public Banner Banner
+        {
+            get { return UnpackBanner(); }
+            set { _packedBanner = PackBanner(value); }
+        }
+        private Banner _banner;
+        [ProtoMember(9)]
+        private byte[] _packedBanner;
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Replace these with weapon index

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs [hunk 27]
```diff
@@ -0,0 +1,32 @@
...
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Missiles.Patches
+{
+    [HarmonyPatch(typeof(Mission), "AddMissileAux")]
+    public class AddMissileAuxPatch
+    {
+        private static void Postfix(int __result, Agent shooterAgent, ref Vec3 direction, ref Vec3 position, ref Mat3 orientation, bool addRigidBody, int forcedMissileIndex)
+        {
+            NetworkMessageBroker.Instance.Publish(Mission.Current, new AgentShoot(shooterAgent, position, direction, orientation, addRigidBody, forcedMissileIndex, __result));
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs:20]: I recommend having separate messages for these events as this one is only used for thrown weapons

Comment (garrettluskey) [inline source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs]: I recommend having separate messages for these events as this one is only used for thrown weapons

File: source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs [hunk 28]
```diff
@@ -0,0 +1,32 @@
...
+        }
+    }
+
+    [HarmonyPatch(typeof(Mission), "AddMissileSingleUsageAux")]
+    public class AddMissileSingleUsageAuxPatch
+    {
+        private static void Postfix(int __result, Agent shooterAgent, ref Vec3 direction, ref Vec3 position, ref Mat3 orientation, bool addRigidBody, int forcedMissileIndex)
+        {
+            NetworkMessageBroker.Instance.Publish(Mission.Current, new AgentShoot(shooterAgent, position, direction, orientation, addRigidBody, forcedMissileIndex, __result));
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs]: I recommend having separate messages for these events as this one is only used for arrows

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 29]
```diff
@@ -0,0 +1,147 @@
...
+
+            if (NetworkAgentRegistry.Instance.IsControlled(payload.What.Agent))
+            {
+
+                Guid shooterAgentGuid = NetworkAgentRegistry.Instance.AgentToId[payload.What.Agent];
+                MissionWeapon missionWeapon;
+
+                if (payload.What.Agent.WieldedWeapon.CurrentUsageItem.IsRangedWeapon && payload.What.Agent.WieldedWeapon.CurrentUsageItem.IsConsumable)
+                {
+                    missionWeapon = payload.What.Agent.WieldedWeapon;
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: instead send a different message type with a weapon index here.
Doing this is a little tricky
Try
```CS
/// <summary>
/// Returns the EquipmentIndex of a given item if it exists in the agent's equipment
/// </summary>
/// <param name="equipment">Equipment to check for item</param>
/// <param name="item">Item to check in equipment</param>
/// <returns>EquipmentIndex of item or EquipmentIndex.None if it was not found in equipment</returns>
public EquipmentIndex GetItemIndex(Equipment equipment, ItemObject item)
{
    foreach (EquipmentIndex idx in (EquipmentIndex[])Enum.GetValues(typeof(EquipmentIndex)))
    {
        if (equipment[idx].Item == item)
        {
            return idx;
        }
    }

    return EquipmentIndex.None;
}
```

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 30]
```diff
@@ -0,0 +1,147 @@
...
+
+                }
+                else
+                {
+                    missionWeapon = payload.What.Agent.WieldedWeapon.AmmoWeapon;
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: instead send a different message type with a weapon index here

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs (hunk 30 above)
Comment (EgardA) [reply source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Why?

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 31]
```diff
@@ -0,0 +1,81 @@
...
+        private void AgentShootRecieve(MessagePayload<NetworkAgentShoot> payload)
+        {
+            NetworkAgentRegistry.Instance.TryGetGroupController(payload.Who as NetPeer, out AgentGroupController agentGroupController);
+
+
+            NetworkAgentShoot shot = payload.What;
+
+            Agent shooter = agentGroupController.ControlledAgents[shot.AgentGuid];
+            MissionWeapon missionWeapon = new MissionWeapon(payload.What.ItemObject, payload.What.ItemModifier, payload.What.Banner);
+            Mat3 orientation = new Mat3(shot.Orientationf, shot.Orientationf, shot.Orientationu);
```
Comment (Ceron257) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]:
```suggestion
            Mat3 orientation = new Mat3(shot.Orientations, shot.Orientationf, shot.Orientationu);
```

File: source/MissionTests/MissionTests.csproj [hunk 32]
```diff
@@ -124,12 +130,14 @@
...
   <ItemGroup>
+    <Analyzer Include="..\..\mb2\bin\Win64_Shipping_Client\TaleWorlds.Core.dll" />
+    <Analyzer Include="..\..\mb2\bin\Win64_Shipping_Client\TaleWorlds.DotNet.dll" />
     <Analyzer Include="..\packages\xunit.analyzers.1.0.0\analyzers\dotnet\cs\xunit.analyzers.dll" />
     <Analyzer Include="..\packages\xunit.analyzers.1.0.0\analyzers\dotnet\cs\xunit.analyzers.fixes.dll" />
   </ItemGroup>
   <ItemGroup>
-    <ProjectReference Include="..\Common\Common.csproj">
-      <Project>{314f078f-41df-4a23-b25c-f558eff83d2a}</Project>
+    <ProjectReference Include="..\Common\Common\Common.csproj">
```
Comment (garrettluskey) [inline source/MissionTests/MissionTests.csproj]: This should be `..\Common\Common.csproj`. Move the common directory to work with that

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 33]
```diff
@@ -0,0 +1,87 @@
...
+    {
+        IContainer container;
+        IBinaryPackageFactory binaryPackageFactory;
+        public MissileHandler()
+        {
+            ContainerBuilder builder = new ContainerBuilder();
+            builder.RegisterModule<MissionModule>();
+            container = builder.Build();
+
+            binaryPackageFactory = container.Resolve<IBinaryPackageFactory>();
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: This is an anti-pattern, do the following instead
```suggestion
        public MissileHandler(IBinaryPackageFactory binaryPackageFactory)
        {
            this.binaryPackageFactory = binaryPackageFactory;
```

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 34]
```diff
@@ -0,0 +1,87 @@
...
+
+            NetworkMessageBroker.Instance.Subscribe<AgentShoot>(AgentShootSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Pass the NetworkMessageBroker as a parameter

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 35]
```diff
@@ -0,0 +1,87 @@
...
+            NetworkMessageBroker.Instance.Subscribe<NetworkAgentShoot>(AgentShootRecieve);
+        }
+
+        ~MissileHandler()
+        {
+            NetworkMessageBroker.Instance.Unsubscribe<AgentShoot>(AgentShootSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Pass the NetworkMessageBroker as a parameter to the constructor.

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 36]
```diff
@@ -0,0 +1,87 @@
...
+            NetworkMessageBroker.Instance.Unsubscribe<NetworkAgentShoot>(AgentShootRecieve);
+        }
+
+        private void AgentShootRecieve(MessagePayload<NetworkAgentShoot> payload)
+        {
+            NetworkAgentRegistry.Instance.TryGetGroupController(payload.Who as NetPeer, out AgentGroupController agentGroupController);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor.

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 37]
```diff
@@ -0,0 +1,87 @@
...
+            GameLoopRunner.RunOnMainThread(() =>
+            {
+                Mission.Current.AddCustomMissile(shooter, missionWeapon, shot.Position, shot.Velocity, orientation, shot.BaseSpeed, shot.Speed, shot.HasRigidBody, null, shot.MissileIndex);
+            });
+        }
+
+        private void AgentShootSend(MessagePayload<AgentShoot> payload)
+        {  
+
+            if (NetworkAgentRegistry.Instance.IsControlled(payload.What.Agent))
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor.

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 38]
```diff
@@ -0,0 +1,87 @@
...
+            {
+                Guid shooterAgentGuid = NetworkAgentRegistry.Instance.AgentToId[payload.What.Agent];
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor.

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 39]
```diff
@@ -0,0 +1,87 @@
...
+                {
+                    missionWeapon = payload.What.MissionWeapon;
+
+                }
+                else
+                {
+                    missionWeapon = payload.What.MissionWeapon.AmmoWeapon;
+                }
+
+                NetworkAgentShoot message = new NetworkAgentShoot(binaryPackageFactory, shooterAgentGuid, payload.What.Position, payload.What.Direction, payload.What.Orientation.s, payload.What.Orientation.f, payload.What.Orientation.u, payload.What.HasRigidBody, missionWeapon.Item, missionWeapon.ItemModifier, missionWeapon.Banner, payload.What.MissileIndex, payload.What.BaseSpeed, payload.What.Speed);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: split this into separate lines

File: source/Missions/Services/Missiles/Message/AgentShoot.cs [hunk 40]
```diff
@@ -0,0 +1,33 @@
...
+        public MissionWeapon MissionWeapon { get; }
+        public Vec3 Position { get; }
+        public Vec3 Direction { get; }
+        public Mat3 Orientation { get; }
+        public float BaseSpeed { get; }
+        public float Speed { get; }
+        public bool HasRigidBody { get; }
+        public int MissileIndex { get; }
+
+        public AgentShoot(Agent agent, MissionWeapon missionWeapon, Vec3 position, Vec3 direction, Mat3 orientation, float baseSpeed, float speed, bool hasRigidBody, int missileIndex)
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/AgentShoot.cs]: split this into separate lines

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 41]
```diff
@@ -0,0 +1,87 @@
...
+using System.Text;
+using System.Threading.Tasks;
+using TaleWorlds.Core;
+using TaleWorlds.Engine;
+using TaleWorlds.Library;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Missiles.Handlers
+{
+    public class MissileHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Make an interface for this class and that interface should be a dependency of `CoopArenaController`

Also add this interface to the DI Module and make remove `.AsSelf().InstancePerLifetimeScope().AutoActivate();`

File: source/Missions/Services/Agents/Patches/AgentPickupPatch.cs [hunk 42]
```diff
@@ -0,0 +1,19 @@
...
+namespace Missions.Services.Agents.Patches
+{
+    [HarmonyPatch(typeof(Agent), "OnItemPickup")]
+    public class AgentPickupPatch
+    {
+        static void Postfix(SpawnedItemEntity spawnedItemEntity, EquipmentIndex weaponPickUpSlotIndex, Agent __instance)
+        {
+            MissionWeapon weapon = spawnedItemEntity.WeaponCopy;
+            WeaponPickedup message = new WeaponPickedup(__instance, weaponPickUpSlotIndex, weapon.Item, weapon.ItemModifier, weapon.Banner);
+            NetworkMessageBroker.Instance.Publish(__instance, message);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Patches/AgentPickupPatch.cs]:
```suggestion
            MessageBroker.Instance.Publish(__instance, message);
```

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 43]
```diff
@@ -0,0 +1,63 @@
...
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Make an interface for this class and that interface should be a dependency of `CoopArenaController`

Also add this interface to the DI Module and make remove `.AsSelf().InstancePerLifetimeScope().AutoActivate();`

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 44]
```diff
@@ -0,0 +1,63 @@
...
+    {
+
+        public WeaponPickupHandler()
+        {
+            ContainerBuilder builder = new ContainerBuilder();
+            builder.RegisterModule<MissionModule>();
+            container = builder.Build();
+
+            binaryPackageFactory = container.Resolve<IBinaryPackageFactory>();
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: This is an anti-pattern, do the following instead
```suggestion
        public WeaponPickupHandler(IBinaryPackageFactory binaryPackageFactory)
        {
            this.binaryPackageFactory = binaryPackageFactory;
```

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 45]
```diff
@@ -0,0 +1,63 @@
...
+
+            NetworkMessageBroker.Instance.Subscribe<WeaponPickedup>(WeaponPickupSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Pass the NetworkMessageBroker as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 46]
```diff
@@ -0,0 +1,63 @@
...
+            NetworkMessageBroker.Instance.Subscribe<NetworkWeaponPickedup>(WeaponPickupReceive);
+        }
+        ~WeaponPickupHandler()
+        {
+            NetworkMessageBroker.Instance.Unsubscribe<WeaponPickedup>(WeaponPickupSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Pass the NetworkMessageBroker as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 47]
```diff
@@ -0,0 +1,63 @@
...
+
+        private static MethodInfo WeaponEquippedMethod = typeof(Agent).GetMethod("WeaponEquipped", BindingFlags.NonPublic | BindingFlags.Instance);
+        private IContainer container;
+        private IBinaryPackageFactory binaryPackageFactory;
+
+        public void WeaponPickupSend(MessagePayload<WeaponPickedup> obj)
+        {
+            Agent agent = obj.Who as Agent;
+
+            NetworkAgentRegistry.Instance.TryGetAgentId(agent, out Guid agentId);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 48]
```diff
@@ -0,0 +1,63 @@
...
+            NetworkWeaponPickedup message = new NetworkWeaponPickedup(binaryPackageFactory, agentId, obj.What.EquipmentIndex, obj.What.WeaponObject, obj.What.WeaponModifier, obj.What.Banner);
+
+            NetworkMessageBroker.Instance.PublishNetworkEvent(message);
+        }
+        public void WeaponPickupReceive(MessagePayload<NetworkWeaponPickedup> obj)
+        {
+            //ItemObject - ItemModifier - Banner creates MissionWeapon
+            MissionWeapon missionWeapon = new MissionWeapon(obj.What.ItemObject, obj.What.ItemModifier, obj.What.Banner);
+
+            NetworkAgentRegistry.Instance.TryGetAgent(obj.What.AgentId, out Agent agent);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs (hunk 22 above)
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Make an interface for this class and that interface should be a dependency of CoopArenaController

Also add this interface to the DI Module and make remove .AsSelf().InstancePerLifetimeScope().AutoActivate();

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 49]
```diff
@@ -0,0 +1,47 @@
...
+    {
+        public WeaponDropHandler()
+        {
+            NetworkMessageBroker.Instance.Subscribe<WeaponDropped>(WeaponDropSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Pass the NetworkMessageBroker as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 50]
```diff
@@ -0,0 +1,47 @@
...
+
+        ~WeaponDropHandler()
+        {
+            NetworkMessageBroker.Instance.Unsubscribe<WeaponDropped>(WeaponDropSend);
+            NetworkMessageBroker.Instance.Unsubscribe<NetworkWeaponDropped>(WeaponDropRecieve);
+        }
+
+        public void WeaponDropSend(MessagePayload<WeaponDropped> obj)
+        {
+            NetworkAgentRegistry.Instance.TryGetAgentId(obj.What.Agent, out Guid agentId);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs [hunk 51]
```diff
@@ -0,0 +1,42 @@
+﻿using Common.Messaging;
+using Common.Network;
+using Missions.Services.Agents.Messages;
+using Missions.Services.Network;
+using System;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    public class ShieldBreakHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs]: Make an interface for this class and that interface should be a dependency of CoopArenaController

Also add this interface to the DI Module and make remove .AsSelf().InstancePerLifetimeScope().AutoActivate();

File: source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs [hunk 52]
```diff
@@ -0,0 +1,42 @@
...
+    {
+        public ShieldBreakHandler() 
+        {
+            NetworkMessageBroker.Instance.Subscribe<ShieldBreak>(ShieldBreakSend);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs]: Pass the NetworkMessageBroker as a parameter to the constructor

File: source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs [hunk 53]
```diff
@@ -0,0 +1,42 @@
...
+        }
+        ~ShieldBreakHandler()
+        {
+            NetworkMessageBroker.Instance.Unsubscribe<ShieldBreak>(ShieldBreakSend);
+            NetworkMessageBroker.Instance.Unsubscribe<NetworkShieldBreak>(ShieldBreakRecieve);
+        }
+
+        public void ShieldBreakSend(MessagePayload<ShieldBreak> payload)
+        {
+            NetworkAgentRegistry.Instance.TryGetAgentId(payload.What.Agent, out Guid agentId);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs]: Pass the NetworkAgentRegistry as a parameter to the constructor

File: source/Missions/Services/Network/Surrogates/Mat3Surrogate.cs [hunk 54]
```diff
@@ -0,0 +1,53 @@
...
+using Autofac.Core;
+using Autofac;
+
+namespace Missions.Services.Network.Surrogates
+{
+    [ProtoContract(SkipConstructor = true)]
+    public readonly struct Mat3Surrogate
+    {
+        [ProtoMember(1)]
+        public byte[] data { get; }
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/Mat3Surrogate.cs]: store this as 3 Vec3s instead
```suggestion
        public Vec3 S { get; }
        [ProtoMember(2)]
        public Vec3 F { get; }
        [ProtoMember(3)]
        public Vec3 U { get; }
```

File: source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs [hunk 55]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    [HarmonyPatch(typeof(Mission), "AddMissileSingleUsageAux")]
+    public class AddMissileSingleUsageAuxPatch
+    {
+        private static void Prefix(Agent shooterAgent, ref MissionWeapon __state)
+        {
+            __state = shooterAgent.WieldedWeapon;
+        }
+        private static void Postfix(int __result, Agent shooterAgent, ref Vec3 direction, ref Vec3 position, ref Mat3 orientation, float baseSpeed, float speed, bool addRigidBody, int forcedMissileIndex, ref MissionWeapon __state)
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs]: make these separate lines, also remove any unused parameters

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 56]
```diff
@@ -0,0 +1,164 @@
...
+        public int MissileIndex { get; }
+
+        [ProtoMember(14)]
+        public float BaseSpeed { get; }
+        [ProtoMember(15)]
+        public float Speed { get; }
+
+        public NetworkAgentShoot(IBinaryPackageFactory packageFactory, Guid agentGuid, Vec3 position, Vec3 velocity, Vec3 orientationS, Vec3 orientationF, Vec3 orientationU, bool hasRigidBody, ItemObject itemObject, ItemModifier itemModifier, Banner banner, int missileIndex, float baseSpeed, float speed)
+        {
+            this.packageFactory = packageFactory;
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: This won't work on deserialize.

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 57]
```diff
@@ -0,0 +1,164 @@
...
+        {
+            get { return UnpackItemModifier(); }
+            set { _packedItemModifier = PackItemModifier(value); }
+        }
+        private ItemModifier _itemModifier;
+        [ProtoMember(9)]
+        private byte[] _packedItemModifier;
+        [ProtoMember(10)]
+        private bool isItemModifierNull = false;
+        public Banner Banner
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Create a surrogate similar to `CharacterObjectSurrogate`

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 58]
```diff
@@ -0,0 +1,164 @@
...
+        {
+            get { return UnpackItemObject(); }
+            set { _packedItemObject = PackItemObject(value); }
+        }
+        private ItemObject _itemObject;
+        [ProtoMember(8)]
+        private byte[] _packedItemObject;
+        private readonly IBinaryPackageFactory packageFactory;
+
+        public ItemModifier ItemModifier
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Create a surrogate similar to `CharacterObjectSurrogate`

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 59]
```diff
@@ -0,0 +1,164 @@
...
+        [ProtoMember(4)]
+        public Vec3 Orientations{ get; }
+        [ProtoMember(5)]
+        public Vec3 Orientationf { get; }
+        [ProtoMember(6)]
+        public Vec3 Orientationu { get; }
+        [ProtoMember(7)]
+        public bool HasRigidBody { get; }
+
+        public ItemObject ItemObject
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Create a surrogate similar to `CharacterObjectSurrogate`

File: source/Missions/Services/Agents/Patches/AgentDamagePatch.cs [hunk 60]
```diff
@@ -37,4 +44,31 @@ static bool Prefix(Agent attacker, Agent victim, Blow b, ref AttackCollisionData
...
+
+            return true;
+        }
+    }
+    [HarmonyPatch(typeof(Agent), nameof(Agent.ChangeWeaponHitPoints))]
+    public class ShieldDamagePatch
+    {
+        static void Postfix(Agent __instance, EquipmentIndex slotIndex, short hitPoints)
+        {
+            if (NetworkAgentRegistry.Instance.TryGetAgentId(__instance, out Guid agentId) == false) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Patches/AgentDamagePatch.cs]: Publish an event after every call of this patch and move the logic to a handler

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs (hunk 56 above)
Comment (EgardA) [reply source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Not sure what to do instead

File: source/Missions/Messages/NetworkMissionJoinInfo.cs [hunk 61]
```diff
@@ -16,8 +19,16 @@ public class NetworkMissionJoinInfo : INetworkEvent
...
+        {
+            get { return UnpackCharacter(); }
+            set { _packedCharacter = PackCharacter(value); }
+        }
+        private CharacterObject _characterObject;
+        private readonly IBinaryPackageFactory packageFactory;
+
         [ProtoMember(3)]
-        public readonly CharacterObject CharacterObject;
+        private byte[] _packedCharacter;
```
Comment (garrettluskey) [inline source/Missions/Messages/NetworkMissionJoinInfo.cs]: Since a surrogate now exists, you can change this to the following
```CS
[ProtoMember(3)]
public CharacterObject CharacterObject { get; }
```

File: source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs [hunk 62]
```diff
@@ -0,0 +1,52 @@
...
+using Missions.Services.Network;
+using System;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    internal interface IShieldBreakHandler : IHandler
+    {
+        void ShieldBreakSend(MessagePayload<ShieldBreak> payload);
+        void ShieldBreakRecieve(MessagePayload<NetworkShieldBreak> payload);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs]: Remove these, all subscribed functions should be private
```suggestion
```

File: source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs [hunk 63]
```diff
@@ -0,0 +1,52 @@
...
+            networkMessageBroker.Subscribe<ShieldBreak>(ShieldBreakSend);
+            networkMessageBroker.Subscribe<NetworkShieldBreak>(ShieldBreakRecieve);
+        }
+        ~ShieldBreakHandler()
+        {
+            networkMessageBroker.Unsubscribe<ShieldBreak>(ShieldBreakSend);
+            networkMessageBroker.Unsubscribe<NetworkShieldBreak>(ShieldBreakRecieve);
+        }
+
+        public void ShieldBreakSend(MessagePayload<ShieldBreak> payload)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs]: Make this private

File: source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs [hunk 64]
```diff
@@ -0,0 +1,52 @@
...
+        {
+            networkAgentRegistry.TryGetAgentId(payload.What.Agent, out Guid agentId);
+
+            NetworkShieldBreak message = new NetworkShieldBreak(agentId, payload.What.EquipmentIndex);
+
+            networkMessageBroker.PublishNetworkEvent(message);
+        }
+
+        public void ShieldBreakRecieve(MessagePayload<NetworkShieldBreak> payload)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldBreakHandler.cs]: Make this private

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 65]
```diff
@@ -0,0 +1,50 @@
...
+using Missions.Services.Network;
+using System;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    internal interface IWeaponDropHandler : IHandler
+    {
+        void WeaponDropSend(MessagePayload<WeaponDropped> obj);
+        void WeaponDropRecieve(MessagePayload<NetworkWeaponDropped> obj);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Remove these, all subscribed functions should be private
```suggestion
```

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 66]
```diff
@@ -0,0 +1,50 @@
...
+            networkMessageBroker.Subscribe<NetworkWeaponDropped>(WeaponDropRecieve);
+        }
+
+        ~WeaponDropHandler()
+        {
+            networkMessageBroker.Unsubscribe<WeaponDropped>(WeaponDropSend);
+            networkMessageBroker.Unsubscribe<NetworkWeaponDropped>(WeaponDropRecieve);
+        }
+
+        public void WeaponDropSend(MessagePayload<WeaponDropped> obj)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Make this private

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 67]
```diff
@@ -0,0 +1,50 @@
...
+        {
+            networkAgentRegistry.TryGetAgentId(obj.What.Agent, out Guid agentId);
+
+            NetworkWeaponDropped message = new NetworkWeaponDropped(agentId, obj.What.EquipmentIndex);
+
+            networkMessageBroker.PublishNetworkEvent(message);
+        }
+
+        public void WeaponDropRecieve(MessagePayload<NetworkWeaponDropped> obj)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Make this private

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 68]
```diff
@@ -0,0 +1,74 @@
...
+using System.Threading.Tasks;
+using TaleWorlds.Core;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    internal interface IWeaponPickupHandler : IHandler
+    {
+        void WeaponPickupSend(MessagePayload<WeaponPickedup> obj);
+        void WeaponPickupReceive(MessagePayload<NetworkWeaponPickedup> obj);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Remove these, all subscribed functions should be private
```suggestion
```

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 69]
```diff
@@ -0,0 +1,74 @@
...
+        }
+        ~WeaponPickupHandler()
+        {
+            networkMessageBroker.Unsubscribe<WeaponPickedup>(WeaponPickupSend);
+            networkMessageBroker.Unsubscribe<NetworkWeaponPickedup>(WeaponPickupReceive);
+        }
+
+        private static MethodInfo WeaponEquippedMethod = typeof(Agent).GetMethod("WeaponEquipped", BindingFlags.NonPublic | BindingFlags.Instance);
+
+        public void WeaponPickupSend(MessagePayload<WeaponPickedup> obj)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Make this private

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 70]
```diff
@@ -0,0 +1,74 @@
...
+                packageFactory, 
+                agentId, 
+                obj.What.EquipmentIndex, 
+                obj.What.WeaponObject, 
+                obj.What.WeaponModifier, 
+                obj.What.Banner);
+
+            networkMessageBroker.PublishNetworkEvent(message);
+        }
+        public void WeaponPickupReceive(MessagePayload<NetworkWeaponPickedup> obj)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Make this private

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 71]
```diff
@@ -0,0 +1,74 @@
...
+            networkMessageBroker.Subscribe<NetworkWeaponPickedup>(WeaponPickupReceive);
+
+        }
+        ~WeaponPickupHandler()
+        {
+            networkMessageBroker.Unsubscribe<WeaponPickedup>(WeaponPickupSend);
+            networkMessageBroker.Unsubscribe<NetworkWeaponPickedup>(WeaponPickupReceive);
+        }
+
+        private static MethodInfo WeaponEquippedMethod = typeof(Agent).GetMethod("WeaponEquipped", BindingFlags.NonPublic | BindingFlags.Instance);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Remove this if it isn't used

File: source/Missions/Services/Agents/Patches/AgentDamagePatch.cs (hunk 60 above)
Comment (garrettluskey) [reply source/Missions/Services/Agents/Patches/AgentDamagePatch.cs]: move the logic to a handler

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs (hunk 59 above)
Comment (garrettluskey) [reply source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: This can be changed to 
```CS
[ProtoMember(8)]
public ItemObject ItemObject { get; }
```

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs (hunk 58 above)
Comment (garrettluskey) [reply source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: This can be changed to 
```CS
[ProtoMember(9)]
public ItemModifier ItemModifier { get; }
```

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs (hunk 57 above)
Comment (garrettluskey) [reply source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: This can be changed to 
```CS
[ProtoMember(11)]
public Banner Banner { get; }
```

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 72]
```diff
@@ -0,0 +1,163 @@
...
+            if (value == null)
+            {
+                isBannerNull = true;
+                return Array.Empty<byte>();
+            }
+            var Banner = new BannerBinaryPackage(value, packageFactory);
+            Banner.Pack();
+
+            return BinaryFormatterSerializer.Serialize(Banner);
+        }
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: This can be removed since we are using surrogates now
```suggestion
```

File: source/Missions/Services/Network/Surrogates/ItemModifierSurrogate.cs [hunk 73]
```diff
@@ -0,0 +1,50 @@
...
+    [ProtoContract(SkipConstructor = true)]
+    public class ItemModifierSurrogate
+    {
+        [ProtoMember(1)]
+        public byte[] data { get; }
+
+        public ItemModifierSurrogate(ItemModifier obj)
+        {
+            // Required to not overwrite data
+            // For some reason protobuf sends 2 character objects
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/ItemModifierSurrogate.cs]: update or remove comments

File: source/Missions/Services/Network/Surrogates/ItemObjectSurrogate.cs [hunk 74]
```diff
@@ -0,0 +1,50 @@
...
+    [ProtoContract(SkipConstructor = true)]
+    public class ItemObjectSurrogate
+    {
+        [ProtoMember(1)]
+        public byte[] data { get; }
+
+        public ItemObjectSurrogate(ItemObject obj)
+        {
+            // Required to not overwrite data
+            // For some reason protobuf sends 2 character objects
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/ItemObjectSurrogate.cs]: update or remove comments

File: source/Missions/Services/Network/Surrogates/BannerSurrogate.cs [hunk 75]
```diff
@@ -0,0 +1,50 @@
+﻿using Common.Serialization;
+using GameInterface.Serialization;
+using GameInterface.Serialization.External;
+using ProtoBuf;
+using TaleWorlds.Core;
+
+namespace Missions.Services.Network.Surrogates
+{
+    [ProtoContract(SkipConstructor = true)]
+    public class BannerSurrogate
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/BannerSurrogate.cs:14]: Add class summary comments

File: source/Missions/Services/Network/Surrogates/ItemModifierSurrogate.cs [hunk 76]
```diff
@@ -0,0 +1,50 @@
+﻿using Common.Serialization;
+using GameInterface.Serialization;
+using GameInterface.Serialization.External;
+using ProtoBuf;
+using TaleWorlds.Core;
+
+namespace Missions.Services.Network.Surrogates
+{
+    [ProtoContract(SkipConstructor = true)]
+    public class ItemModifierSurrogate
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/ItemModifierSurrogate.cs:13]: Add class summary comments

File: source/Missions/Services/Network/Surrogates/ItemObjectSurrogate.cs [hunk 77]
```diff
@@ -0,0 +1,50 @@
+﻿using Common.Serialization;
+using GameInterface.Serialization;
+using GameInterface.Serialization.External;
+using ProtoBuf;
+using TaleWorlds.Core;
+
+namespace Missions.Services.Network.Surrogates
+{
+    [ProtoContract(SkipConstructor = true)]
+    public class ItemObjectSurrogate
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/ItemObjectSurrogate.cs:13]: Add class summary comments

File: source/Missions/Services/Network/Surrogates/Mat3Surrogate.cs [hunk 78]
```diff
@@ -0,0 +1,48 @@
...
+using System.Threading.Tasks;
+using TaleWorlds.Library;
+using Common.Serialization;
+using Autofac.Core;
+using Autofac;
+
+namespace Missions.Services.Network.Surrogates
+{
+    [ProtoContract(SkipConstructor = true)]
+    public readonly struct Mat3Surrogate
```
Comment (garrettluskey) [inline source/Missions/Services/Network/Surrogates/Mat3Surrogate.cs:20]: Add class summary comments

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 79]
```diff
@@ -0,0 +1,163 @@
...
+using TaleWorlds.Library;
+using TaleWorlds.MountAndBlade;
+using Common.Serialization;
+using System.Reflection;
+using Autofac;
+
+namespace Missions.Services.Missiles.Message
+{
+    [ProtoContract(SkipConstructor = true)]
+    public class NetworkAgentShoot : INetworkEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs:13]: Add class summary comments

File: source/Missions/Services/Missiles/Message/AgentShoot.cs [hunk 80]
```diff
@@ -0,0 +1,41 @@
+﻿using Common.Messaging;
+using TaleWorlds.Core;
+using TaleWorlds.Library;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Missiles.Message
+{
+    public readonly struct AgentShoot : IEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/AgentShoot.cs:11]: Add class summary comments

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 81]
```diff
@@ -0,0 +1,95 @@
...
+using Missions.Services.Agents.Packets;
+using Missions.Services.Missiles.Message;
+using Missions.Services.Network;
+using System;
+using TaleWorlds.Library;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Missiles.Handlers
+{
+    internal interface IMissileHandler : IHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Add class summary comments

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 82]
```diff
@@ -0,0 +1,95 @@
...
+    {
+        void AgentShootSend(MessagePayload<AgentShoot> payload);
+        void AgentShootRecieve(MessagePayload<NetworkAgentShoot> payload);
+    }
+
+    public class MissileHandler : IMissileHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs:26]: Add `<inheritdoc />`

File: source/Missions/Services/Agents/Messages/NetworkWeaponDropped.cs [hunk 83]
```diff
@@ -0,0 +1,26 @@
...
+using System;
+using TaleWorlds.Core;
+using TaleWorlds.Library;
+using TaleWorlds.MountAndBlade;
+using static TaleWorlds.MountAndBlade.Mission;
+
+namespace Missions.Services.Agents.Messages
+{
+    [ProtoContract(SkipConstructor = true)]
+    public readonly struct NetworkWeaponDropped : INetworkEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/NetworkWeaponDropped.cs:12]: Add class summary comments

File: source/Missions/MissionModule.cs [hunk 84]
```diff
@@ -52,12 +58,17 @@ protected override void Load(ContainerBuilder builder)
...
             builder.RegisterType<RandomEquipmentGenerator>().As<IRandomEquipmentGenerator>();
             builder.RegisterType<PacketManager>().As<IPacketManager>().InstancePerLifetimeScope();
             builder.RegisterType<EventPacketHandler>().AsSelf().InstancePerLifetimeScope();
             builder.RegisterType<MovementHandler>().AsSelf().InstancePerLifetimeScope();
-            
+            builder.RegisterType<MissileHandler>().As<IMissileHandler>().InstancePerLifetimeScope().AutoActivate();
+            builder.RegisterType<WeaponPickupHandler>().As<IWeaponPickupHandler>().InstancePerLifetimeScope().AutoActivate();
+            builder.RegisterType<WeaponDropHandler>().As<IWeaponDropHandler>().InstancePerLifetimeScope().AutoActivate();
+            builder.RegisterType<ShieldBreakHandler>().As<IShieldBreakHandler>().InstancePerLifetimeScope().AutoActivate();
+            builder.RegisterType<AgentDamageHandler>().As<IAgentDamageHandler>().InstancePerLifetimeScope().AutoActivate();
```
Comment (garrettluskey) [inline source/Missions/MissionModule.cs]:
```suggestion
            builder.RegisterType<MissileHandler>().As<IMissileHandler>();
            builder.RegisterType<WeaponPickupHandler>().As<IWeaponPickupHandler>();
            builder.RegisterType<WeaponDropHandler>().As<IWeaponDropHandler>();
            builder.RegisterType<ShieldBreakHandler>().As<IShieldBreakHandler>();
            builder.RegisterType<AgentDamageHandler>().As<IAgentDamageHandler>();
```

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 85]
```diff
@@ -0,0 +1,108 @@
...
+using Missions.Services.Network;
+using System;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    internal interface IAgentDamageHandler : IHandler
+    {
+        void AgentDamageSend(MessagePayload<AgentDamage> payload);
+        void AgentDamageRecieve(MessagePayload<NetworkAgentDamage> payload);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: Remove these, all subscribed functions should be private
```suggestion
```

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 86]
```diff
@@ -0,0 +1,95 @@
...
+using System;
+using TaleWorlds.Library;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Missiles.Handlers
+{
+    internal interface IMissileHandler : IHandler
+    {
+        void AgentShootSend(MessagePayload<AgentShoot> payload);
+        void AgentShootRecieve(MessagePayload<NetworkAgentShoot> payload);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Remove these, all subscribed functions should be private
```suggestion
```

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 87]
```diff
@@ -0,0 +1,60 @@
...
+        public Banner Banner { get; }
+        [ProtoMember(11)]
+        public int MissileIndex { get; }
+
+        [ProtoMember(12)]
+        public float BaseSpeed { get; }
+        [ProtoMember(13)]
+        public float Speed { get; }
+
+        public NetworkAgentShoot(Guid agentGuid, Vec3 position, Vec3 velocity, Vec3 orientationS, Vec3 orientationF, Vec3 orientationU, bool hasRigidBody, ItemObject itemObject, ItemModifier itemModifier, Banner banner, int missileIndex, float baseSpeed, float speed)
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Make this multiple lines for readability

File: source/Missions/Services/Agents/Messages/NetworkWeaponPickedup.cs [hunk 88]
```diff
@@ -0,0 +1,136 @@
...
+    [ProtoContract(SkipConstructor = true)]
+    public class NetworkWeaponPickedup : INetworkEvent
+    {   
+        [ProtoMember(1)]
+        public Guid AgentId { get; }
+
+        [ProtoMember(2)]
+        public EquipmentIndex EquipmentIndex { get; }
+
+        public ItemObject ItemObject
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/NetworkWeaponPickedup.cs]: Use surrogates instead

File: source/Missions/Services/Agents/Messages/WeaponPickedup.cs [hunk 89]
```diff
@@ -0,0 +1,29 @@
...
+    /// </summary>
+    public readonly struct WeaponPickedup : IEvent
+    {
+        public Agent Agent { get; }
+        public EquipmentIndex EquipmentIndex { get; }
+        public ItemObject WeaponObject { get; }
+        public ItemModifier WeaponModifier { get; }
+        public Banner Banner { get; }
+
+        public WeaponPickedup(Agent agent, EquipmentIndex equipmentIndex, ItemObject weaponObject, ItemModifier itemModifier, Banner banner)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/WeaponPickedup.cs]: make this multiple lines for readability

File: source/Missions/Services/Agents/Patches/AgentDamagePatch.cs [hunk 90]
```diff
@@ -16,25 +24,40 @@ public class AgentDamagePatch
     {
         static bool Prefix(Agent attacker, Agent victim, Blow b, ref AttackCollisionData collisionData)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Patches/AgentDamagePatch.cs]: Change this to `private static void`

File: source/Missions/Services/Agents/Patches/AgentDamagePatch.cs [hunk 91]
```diff
@@ -16,25 +24,40 @@ public class AgentDamagePatch
...
+            if (NetworkAgentRegistry.Instance.TryGetAgentId(__instance, out Guid agentId) == false) return;
+
+            if (NetworkAgentRegistry.Instance.IsControlled(agentId) == false) return;
+
+            if (hitPoints <= 0) 
+            {
+                ShieldBreak shieldDamage = new ShieldBreak(__instance, slotIndex);
+                NetworkMessageBroker.Instance.Publish(__instance, shieldDamage);
+            }
+        }
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Patches/AgentDamagePatch.cs]: Rename `ShieldBreakHandler` to `ShieldDamageHandler`, move this logic there, and subscribe to this event
```suggestion
            ShieldDamaged shieldDamaged = new ShieldDamaged(__instance, slotIndex);
            NetworkMessageBroker.Instance.Publish(__instance, shieldDamaged);
        }
```

File: source/Missions/Services/Agents/Patches/AgentDamagePatch.cs [hunk 92]
```diff
@@ -16,25 +24,40 @@ public class AgentDamagePatch
...
+            // Only allow damage from controlled agents
+            if (!NetworkAgentRegistry.Instance.IsControlled(affectorAgent)) return false;
 
             return true;
         }
     }
+    [HarmonyPatch(typeof(Agent), nameof(Agent.ChangeWeaponHitPoints))]
+    public class ShieldDamagePatch
+    {
+        static void Postfix(Agent __instance, EquipmentIndex slotIndex, short hitPoints)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Patches/AgentDamagePatch.cs]: Add `private` here and anywhere else that doesn't exist (within this file set)

File: source/Missions/MissionModule.cs [hunk 93]
```diff
@@ -52,12 +58,17 @@ protected override void Load(ContainerBuilder builder)
...
             builder.RegisterType<RandomEquipmentGenerator>().As<IRandomEquipmentGenerator>();
             builder.RegisterType<PacketManager>().As<IPacketManager>().InstancePerLifetimeScope();
             builder.RegisterType<EventPacketHandler>().AsSelf().InstancePerLifetimeScope();
             builder.RegisterType<MovementHandler>().AsSelf().InstancePerLifetimeScope();
-            
+            builder.RegisterType<MissileHandler>().As<IMissileHandler>();
+            builder.RegisterType<WeaponPickupHandler>().As<IWeaponPickupHandler>();
+            builder.RegisterType<WeaponDropHandler>().As<IWeaponDropHandler>();
+            builder.RegisterType<ShieldBreakHandler>().As<IShieldBreakHandler>();
+            builder.RegisterType<AgentDamageHandler>().As<IAgentDamageHandler>();
```
Comment (garrettluskey) [inline source/Missions/MissionModule.cs]: All interfaces here need to be added to the `CoopArenaController` constructor as a parameter.

This is needed so that when the `CoopArenaController` is created, these objects are also created by the DI framework.

I.E.
```CS
CoopArenaController(
    INetworkMessageBroker networkMessageBroker,
    INetworkAgentRegistry agentRegistry, 
    IRandomEquipmentGenerator equipmentGenerator,
    IBinaryPackageFactory packageFactory,
    IMissileHandler missileHandler,
    IWeaponDropHandler weaponDropHandler,
    ...)
```

File: source/Missions/Messages/NetworkMissionJoinInfo.cs [hunk 94]
```diff
@@ -27,22 +30,65 @@ public class NetworkMissionJoinInfo : INetworkEvent
...
 
-        public NetworkMissionJoinInfo(
-            CharacterObject characterObject,
-            bool isPlayerAlive, 
-            Guid playerId, 
-            Vec3 startingPosition, 
-            Guid[] unitId, 
-            Vec3[] unitStartingPosition, 
-            string[] unitIdString)
+        public Equipment Equipment
```
Comment (garrettluskey) [inline source/Missions/Messages/NetworkMissionJoinInfo.cs]: Update this to a surrogate

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs (hunk 56 above)
Comment (garrettluskey) [reply source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Use surrogates instead

File: source/MissionTests/MissionTests.csproj (hunk 32 above)
Comment (garrettluskey) [reply source/MissionTests/MissionTests.csproj]: You will have to physically move the Common project up a directory

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 95]
```diff
@@ -0,0 +1,112 @@
...
+        {
+            networkMessageBroker.Unsubscribe<AgentDamage>(AgentDamageSend);
+            networkMessageBroker.Unsubscribe<NetworkAgentDamage>(AgentDamageRecieve);
+        }
+
+        private void AgentDamageSend(MessagePayload<AgentDamage> payload)
+        {
+
+            // first, check if the attacker exists in the agent to ID groud, if not, no networking is needed (not a network agent)
+            if (NetworkAgentRegistry.Instance.TryGetAgentId(payload.What.AttackerAgent, out Guid attackerId) == false) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: use `networkAgentRegistry` instead

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 96]
```diff
@@ -0,0 +1,112 @@
...
+
+            // next, check if the attacker is one of ours, if not, no networking is needed (not our agent dealing damage)
+            if (NetworkAgentRegistry.Instance.IsControlled(attackerId) == false) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: use `networkAgentRegistry` instead

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 97]
```diff
@@ -0,0 +1,112 @@
...
+
+            // If there is package factory cannot be resolved, do default behavior
+            if (ContainerProvider.TryResolve<IBinaryPackageFactory>(out var packageFactory) == false) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: Remove since this isn't used

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 98]
```diff
@@ -0,0 +1,73 @@
...
+    }
+    /// <inheritdoc/>
+    public class WeaponPickupHandler : IWeaponPickupHandler
+    {
+        readonly IBinaryPackageFactory packageFactory;
+        readonly NetworkAgentRegistry networkAgentRegistry;
+        readonly NetworkMessageBroker networkMessageBroker;
+        public WeaponPickupHandler(IBinaryPackageFactory packageFactory, NetworkAgentRegistry networkAgentRegistry, NetworkMessageBroker networkMessageBroker)
+        {
+            this.packageFactory = packageFactory;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Remove since this isn't used

File: source/Missions/Messages/NetworkMissionJoinInfo.cs [hunk 99]
```diff
@@ -26,15 +32,15 @@ public class NetworkMissionJoinInfo : INetworkEvent
...
-            bool isPlayerAlive, 
-            Guid playerId, 
-            Vec3 startingPosition, 
-            Guid[] unitId, 
-            Vec3[] unitStartingPosition, 
-            string[] unitIdString)
+        [ProtoMember(10)]
+        public readonly float PlayerHealth;
+
+        public NetworkMissionJoinInfo(CharacterObject characterObject, bool isPlayerAlive, Guid playerId, Vec3 startingPosition, float health, Guid[] unitId, Vec3[] unitStartingPosition, string[] unitIdString, float[] unitHealthList)
```
Comment (garrettluskey) [inline source/Missions/Messages/NetworkMissionJoinInfo.cs]: make this multiple lines for readability

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 100]
```diff
@@ -0,0 +1,112 @@
...
+using Missions.Services.Network;
+using System;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Handlers
+{
+    /// <summary>
+    /// Handler for agent damage in a battle
+    /// </summary>
+    public interface IAgentDamageHandler : IHandler
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: Add inheritance to IDisposable
Do the same for the other handlers in the PR as well
```suggestion
    public interface IAgentDamageHandler : IHandler, IDisposable
```

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 101]
```diff
@@ -0,0 +1,112 @@
...
+            this.networkMessageBroker = networkMessageBroker;
+
+            networkMessageBroker.Subscribe<AgentDamage>(AgentDamageSend);
+            networkMessageBroker.Subscribe<NetworkAgentDamage>(AgentDamageRecieve);
+        }
+        ~AgentDamageHandler()
+        {
+            networkMessageBroker.Unsubscribe<AgentDamage>(AgentDamageSend);
+            networkMessageBroker.Unsubscribe<NetworkAgentDamage>(AgentDamageRecieve);
+        }
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: Do the same for the other handlers in the PR as well
```suggestion
        ~AgentDamageHandler()
        {
            Dispose();
        }
        
        public void Dispose()
        {
            networkMessageBroker.Unsubscribe<AgentDamage>(AgentDamageSend);
            networkMessageBroker.Unsubscribe<NetworkAgentDamage>(AgentDamageRecieve);
        }
```

File: source/Missions/Services/Agents/Messages/NetworkAgentDamage.cs [hunk 102]
```diff
@@ -21,7 +24,7 @@ public class AgentDamageData : INetworkEvent
         [ProtoMember(4)]
         public AttackCollisionData AttackCollisionData { get; }
 
-        public AgentDamageData(
+        public NetworkAgentDamage(
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/NetworkAgentDamage.cs]: All events should be past-tense
```suggestion
        public NetworkAgentDamaged(
```

File: source/Missions/Services/Agents/Messages/NetworkWeaponPickedup.cs [hunk 103]
```diff
@@ -0,0 +1,40 @@
...
+        [ProtoMember(3)]
+        public ItemObject ItemObject { get; }
+
+        [ProtoMember(4)]
+        public ItemModifier ItemModifier { get; }
+
+        [ProtoMember(5)]
+        public Banner Banner { get; }
+
+        public NetworkWeaponPickedup(Guid agentId, EquipmentIndex equipmentIndex, ItemObject weaponObject, ItemModifier itemModifier, Banner banner)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/NetworkWeaponPickedup.cs]: make this multiple lines for readability

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 104]
```diff
@@ -0,0 +1,96 @@
...
+
+        private void AgentShootRecieve(MessagePayload<NetworkAgentShoot> payload)
+        {
+            networkAgentRegistry.TryGetGroupController(payload.Who as NetPeer, out AgentGroupController agentGroupController);
+
+
+            NetworkAgentShoot shot = payload.What;
+
+            Agent shooter = agentGroupController.ControlledAgents[shot.AgentGuid];
+            MissionWeapon missionWeapon = new MissionWeapon(payload.What.ItemObject, payload.What.ItemModifier, payload.What.Banner);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: make multiple lines for readability

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 105]
```diff
@@ -0,0 +1,96 @@
...
+            Mat3 orientation = new Mat3(shot.Orientations, shot.Orientationf, shot.Orientationu);
+
+            GameLoopRunner.RunOnMainThread(() =>
+            {
+                Mission.Current.AddCustomMissile(shooter, missionWeapon, shot.Position, shot.Velocity, orientation, shot.BaseSpeed, shot.Speed, shot.HasRigidBody, null, shot.MissileIndex);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: make multiple lines for readability

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 106]
```diff
@@ -0,0 +1,96 @@
...
+
+        private void AgentShootSend(MessagePayload<AgentShoot> payload)
+        {  
+
+            if (networkAgentRegistry.IsControlled(payload.What.Agent))
+            {
+                Guid shooterAgentGuid = networkAgentRegistry.AgentToId[payload.What.Agent];
+                MissionWeapon missionWeapon;
+
+                if (payload.What.MissionWeapon.CurrentUsageItem.IsRangedWeapon && payload.What.MissionWeapon.CurrentUsageItem.IsConsumable)
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: make multiple lines for readability

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 107]
```diff
@@ -0,0 +1,72 @@
...
+        public Banner Banner { get; }
+        [ProtoMember(11)]
+        public int MissileIndex { get; }
+
+        [ProtoMember(12)]
+        public float BaseSpeed { get; }
+        [ProtoMember(13)]
+        public float Speed { get; }
+
+        public NetworkAgentShoot(Guid agentGuid,
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]:
```suggestion
        public NetworkAgentShoot(
            Guid agentGuid, 
```

File: source/Missions/Services/Agents/Messages/ShieldHealthRemaining.cs [hunk 108]
```diff
@@ -0,0 +1,28 @@
...
+using System.Threading.Tasks;
+using TaleWorlds.Core;
+using TaleWorlds.MountAndBlade;
+
+namespace Missions.Services.Agents.Messages
+{
+    /// <summary>
+    /// Internal event for agent shield damage
+    /// </summary>
+    public readonly struct ShieldHealthRemaining : IEvent
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Messages/ShieldHealthRemaining.cs]: Rename to `ShieldDamaged`
```suggestion
    public readonly struct ShieldDamaged : IEvent
```

File: source/Missions/Messages/NetworkMissionJoinInfo.cs [hunk 109]
```diff
@@ -17,7 +23,7 @@ public class NetworkMissionJoinInfo : INetworkEvent
         [ProtoMember(2)]
         public readonly Vec3 StartingPosition;
         [ProtoMember(3)]
-        public readonly CharacterObject CharacterObject;
+        public CharacterObject CharacterObject { get; }
```
Comment (garrettluskey) [inline source/Missions/Messages/NetworkMissionJoinInfo.cs]: If readonly works here, change everything in this class to use `readonly` for consistency

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 110]
```diff
@@ -0,0 +1,112 @@
...
+
+            // next, check if the attacker is one of ours, if not, no networking is needed (not our agent dealing damage)
+            if (networkAgentRegistry.IsControlled(attackerId) == false) return;
+
+            // If there is package factory cannot be resolved, do default behavior
+            if (ContainerProvider.TryResolve<IBinaryPackageFactory>(out var packageFactory) == false) return;
+
+            networkAgentRegistry.TryGetAgentId(payload.What.VictimAgent, out Guid victimId);
+
+            NetworkAgentDamage message = new NetworkAgentDamage(attackerId, victimId, payload.What.AttackCollisionData, payload.What.Blow);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: make this multiple lines for readability

File: source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs [hunk 111]
```diff
@@ -0,0 +1,92 @@
...
+            ref Vec3 position,
+            ref Mat3 orientation,
+            float baseSpeed,
+            float speed, 
+            bool addRigidBody, 
+            ref MissionWeapon __state)
+        {
+            if (NetworkAgentRegistry.Instance.IsControlled(shooterAgent))
+            {
+                AgentShoot message = new AgentShoot(shooterAgent, __state, position, direction, orientation, baseSpeed, speed, addRigidBody, __result);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs]: make multiple lines for readability

File: source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs [hunk 112]
```diff
@@ -0,0 +1,92 @@
...
+            ref Vec3 position, 
+            ref Mat3 orientation, 
+            float baseSpeed, 
+            float speed, 
+            bool addRigidBody, 
+            ref MissionWeapon __state)
+        {
+            if (NetworkAgentRegistry.Instance.IsControlled(shooterAgent))
+            {
+                AgentShoot message = new AgentShoot(shooterAgent, __state, position, direction, orientation, baseSpeed, speed, addRigidBody, __result);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Patches/MissileAuxPatches.cs]: make multiple lines for readability

**Review by garrettluskey — CHANGES_REQUESTED** [review]

File: source/Missions/Services/Agents/Handlers/ShieldDamageHandler.cs [hunk 113]
```diff
@@ -0,0 +1,64 @@
...
+            NetworkShieldBreak message = new NetworkShieldBreak(agentId, payload.What.EquipmentIndex);
+
+            networkMessageBroker.PublishNetworkEvent(message);
+        }
+
+        private void ShieldBreakRecieve(MessagePayload<NetworkShieldBreak> payload)
+        {
+            networkAgentRegistry.TryGetAgent(payload.What.AgentGuid, out Agent agent);
+
+            if (!agent.Equipment[payload.What.EquipmentIndex].IsEmpty)
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldDamageHandler.cs]: Invert and add logging and return if this line fails
```suggestion
            if (agent.Equipment[payload.What.EquipmentIndex].IsEmpty) {
                // TODO add logging
                return;
            }
```

File: source/Missions/Services/Agents/Handlers/ShieldDamageHandler.cs [hunk 114]
```diff
@@ -0,0 +1,64 @@
...
+            if (networkAgentRegistry.IsControlled(agentId) == false) return;
+
+            NetworkShieldBreak message = new NetworkShieldBreak(agentId, payload.What.EquipmentIndex);
+
+            networkMessageBroker.PublishNetworkEvent(message);
+        }
+
+        private void ShieldBreakRecieve(MessagePayload<NetworkShieldBreak> payload)
+        {
+            networkAgentRegistry.TryGetAgent(payload.What.AgentGuid, out Agent agent);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/ShieldDamageHandler.cs]: Add logging and return if this line fails

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 115]
```diff
@@ -0,0 +1,60 @@
...
+        {
+            networkMessageBroker.Unsubscribe<WeaponDropped>(WeaponDropSend);
+            networkMessageBroker.Unsubscribe<NetworkWeaponDropped>(WeaponDropRecieve);
+        }
+
+        private void WeaponDropSend(MessagePayload<WeaponDropped> obj)
+        {
+            if (!networkAgentRegistry.IsControlled(obj.What.Agent)) return;
+            
+            networkAgentRegistry.TryGetAgentId(obj.What.Agent, out Guid agentId);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]:
```suggestion
            if (networkAgentRegistry.TryGetAgentId(obj.What.Agent, out Guid agentId) == false) {
                // TODO add logging
                return;
            }
```

File: source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs [hunk 116]
```diff
@@ -0,0 +1,60 @@
...
+
+        public void Dispose()
+        {
+            networkMessageBroker.Unsubscribe<WeaponDropped>(WeaponDropSend);
+            networkMessageBroker.Unsubscribe<NetworkWeaponDropped>(WeaponDropRecieve);
+        }
+
+        private void WeaponDropSend(MessagePayload<WeaponDropped> obj)
+        {
+            if (!networkAgentRegistry.IsControlled(obj.What.Agent)) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponDropHandler.cs]: Instead of using `!` use `== false` instead. I'm going to add it to our coding standard whenever I get to that
```suggestion
            if (networkAgentRegistry.IsControlled(obj.What.Agent) == false) return;
```

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 117]
```diff
@@ -0,0 +1,76 @@
...
+
+        public void Dispose()
+        {
+            networkMessageBroker.Unsubscribe<WeaponPickedup>(WeaponPickupSend);
+            networkMessageBroker.Unsubscribe<NetworkWeaponPickedup>(WeaponPickupReceive);
+        }
+
+        private void WeaponPickupSend(MessagePayload<WeaponPickedup> obj)
+        {
+            if (!networkAgentRegistry.IsControlled(obj.What.Agent)) return;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]: Instead of using `!` use `== false` instead. I'm going to add it to our coding standard whenever I get to that
```suggestion
            if (networkAgentRegistry.IsControlled(obj.What.Agent) == false) return;
```

File: source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs [hunk 118]
```diff
@@ -0,0 +1,76 @@
...
+
+            networkAgentRegistry.TryGetAgentId(obj.What.Agent, out Guid agentId);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/WeaponPickupHandler.cs]:
```suggestion
            if (networkAgentRegistry.TryGetAgentId(obj.What.Agent, out Guid agentId) == false) {
                // TODO add logging
                return;
            }
```

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 119]
```diff
@@ -0,0 +1,117 @@
...
+
+        public void Dispose()
+        {
+            networkMessageBroker.Unsubscribe<AgentShoot>(AgentShootSend);
+            networkMessageBroker.Unsubscribe<NetworkAgentShoot>(AgentShootRecieve);
+        }
+
+        private void AgentShootRecieve(MessagePayload<NetworkAgentShoot> payload)
+        {
+            networkAgentRegistry.TryGetGroupController(payload.Who as NetPeer, out AgentGroupController agentGroupController);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Return if this fails
```suggestion
            if (networkAgentRegistry.TryGetGroupController(payload.Who as NetPeer, out AgentGroupController agentGroupController) == false) return;
```

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 120]
```diff
@@ -0,0 +1,117 @@
...
+            NetworkAgentShoot shot = payload.What;
+
+            Agent shooter = agentGroupController.ControlledAgents[shot.AgentGuid];
+
+            MissionWeapon missionWeapon = new MissionWeapon(
+                payload.What.ItemObject, 
+                payload.What.ItemModifier, 
+                payload.What.Banner);
+
+            Mat3 orientation = new Mat3(shot.Orientations, shot.Orientationf, shot.Orientationu);
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Try using the Mat3 surrogate in the `NetworkAgentShoot` class instead of recreating it here. If that doesn't work then this is fine

File: source/Missions/Services/Missiles/Handlers/MissileHandler.cs [hunk 121]
```diff
@@ -0,0 +1,117 @@
...
+                    missionWeapon = payload.What.MissionWeapon.AmmoWeapon;
+                }
+
+                NetworkAgentShoot message = new NetworkAgentShoot( 
+                    shooterAgentGuid, 
+                    payload.What.Position, 
+                    payload.What.Direction, 
+                    payload.What.Orientation.s, 
+                    payload.What.Orientation.f, 
+                    payload.What.Orientation.u,
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Handlers/MissileHandler.cs]: Try using the Mat3 surrogate instead

File: source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs [hunk 122]
```diff
@@ -0,0 +1,73 @@
...
+        [ProtoMember(2)]
+        public Vec3 Position { get; }
+        [ProtoMember(3)]
+        public Vec3 Velocity { get; }
+        [ProtoMember(4)]
+        public Vec3 Orientations{ get; }
+        [ProtoMember(5)]
+        public Vec3 Orientationf { get; }
+        [ProtoMember(6)]
+        public Vec3 Orientationu { get; }
```
Comment (garrettluskey) [inline source/Missions/Services/Missiles/Message/NetworkAgentShoot.cs]: Try using the Mat3 surrogate instead

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 123]
```diff
@@ -0,0 +1,117 @@
...
+        private void AgentDamageSend(MessagePayload<AgentDamage> payload)
+        {
+
+            // first, check if the attacker exists in the agent to ID groud, if not, no networking is needed (not a network agent)
+            if (networkAgentRegistry.TryGetAgentId(payload.What.AttackerAgent, out Guid attackerId) == false) return;
+
+            // next, check if the attacker is one of ours, if not, no networking is needed (not our agent dealing damage)
+            if (networkAgentRegistry.IsControlled(attackerId) == false) return;
+
+            networkAgentRegistry.TryGetAgentId(payload.What.VictimAgent, out Guid victimId);
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs]: Add logging here when failing and return
```suggestion
            if (networkAgentRegistry.TryGetAgentId(payload.What.VictimAgent, out Guid victimId) == false)
            {
                Logger.Warning("Unable to get id for {agent} in {class}", payload.What.VictimAgent, typeof(AgentDamageHandler);
                return;
            }
```

File: source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs [hunk 124]
```diff
@@ -0,0 +1,117 @@
...
+    /// Handler for agent damage in a battle
+    /// </summary>
+    public interface IAgentDamageHandler : IHandler, IDisposable
+    {
+
+    }
+    /// <inheritdoc/>
+    public class AgentDamageHandler : IAgentDamageHandler
+    {
+        readonly INetworkAgentRegistry networkAgentRegistry;
```
Comment (garrettluskey) [inline source/Missions/Services/Agents/Handlers/AgentDamageHandler.cs:26]:
```suggestion
        readonly static ILogger Logger = LogManager.GetLogger<AgentDamageHandler>();
        readonly INetworkAgentRegistry networkAgentRegistry;
```

**Review by garrettluskey — CHANGES_REQUESTED** [review]

**Review by garrettluskey — APPROVED** [review]
Wowee
