### PR TITLE
Player transfer bug fixes

### LINKED ISSUE #45: Serializer is missing transfer items
Objects after transfer are missing data items. Add all valid serialized to SerializerFactory

### LINKED ISSUE #76: Client needs to be granted control to new party
RailNetPeer needs to be assigned to newly created party.

### PR DESCRIPTION
**Pull request by garrettluskey**
Many issues with hero transfer fixed in this. Object Transaction system was scrapped for this update and will remain as an on-hold until we see more value in it. SyncStore works fine for now. Mainly serialization updates and manager updates to pass around newly created heros.

### CODE REVIEW

File: source/Coop/Mod/Managers/ClientManager.cs [hunk 1]
```diff
@@ -1,51 +1,41 @@
...
+        public ClientManager(LoadResult saveGameData, string partyName) : base(saveGameData) { m_PartyName = partyName; }
 
         public delegate void OnOnLoadFinishedEventHandler(object source, EventArgs e);
         public static event OnOnLoadFinishedEventHandler OnLoadFinishedEvent;
-
         public override void OnLoadFinished()
         {
             base.OnLoadFinished();
-
+            Parallel.ForEach(MobileParty.All, (party) =>
```
Comment (araex) [inline source/Coop/Mod/Managers/ClientManager.cs]: Feels kinda weird to express it that way. The code is not actually thread save, it only works under the assumption that only 1 party.Name == m_PartyName.

How about this instead:
```C#
MobileParty playerParty = MobileParty.All.AsParallel().SingleOrDefault(party => party.Name.ToString() == m_PartyName);
if(playerParty != null)
{
   // ...
}
```

File: source/Coop/Mod/Serializers/CustomSerializers/PlayerHeroSerializer.cs [hunk 2]
```diff
@@ -159,7 +159,25 @@ public override object Deserialize()
...
 
-            return base.Deserialize(hero);
+            
+
+            ConstructorInfo ctor = typeof(HeroDeveloper).GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance,
+                                    null, new Type[] { typeof(Hero) }, null);
+
+            HeroDeveloper newDeveloper = (HeroDeveloper)ctor.Invoke(new object[] { hero });
+            hero.GetType()
+                .GetField("_heroDeveloper", BindingFlags.NonPublic | BindingFlags.Instance)
```
Comment (araex) [inline source/Coop/Mod/Serializers/CustomSerializers/PlayerHeroSerializer.cs:169]: Do you happen to know of a way to get this to yield a compile error if the field does not exist? Maybe trough a public property that uses the field internally?

Since they are refactoring game DLLs, these hard coded variable names may compile, but no longer work in a new game version. Some way to at least notice that at compile time would be great.

**Review by araex — APPROVED** [review]
Looks good

**Comment by araex** [comment]
I pushed 2 compile fixes in 32ffda5 . Most likely these are due to the latest update.

File: source/Coop/Mod/Serializers/CustomSerializers/PlayerHeroSerializer.cs (hunk 2 above)
Comment (garrettluskey) [reply source/Coop/Mod/Serializers/CustomSerializers/PlayerHeroSerializer.cs:169]: .SetValue will throw a compiler exception due to FieldInfo being null

File: source/Coop/Mod/Managers/ClientManager.cs (hunk 1 above)
Comment (garrettluskey) [reply source/Coop/Mod/Managers/ClientManager.cs]: I agree
